{"name": "登录测试用例", "status": "broken", "statusDetails": {"message": "AttributeError: 'Android_UI_Client' object has no attribute 'driver'", "trace": "self = <cases.app_ui.android.test_login.TestLogin object at 0x0000023EC8226C10>, app = <base.android.android_ui_client.Android_UI_Client object at 0x0000023EC8262A50>\n\n    @pytest.fixture(scope=\"function\", autouse=True)\n    def setup(self, app):\n        self.ocr = OCRProcessor()\n>       self.lg = LoginPage(app.driver, app.appium_hub)\nE       AttributeError: 'Android_UI_Client' object has no attribute 'driver'\n\ncases\\app_ui\\android\\test_login.py:19: AttributeError"}, "description": "\n        登录测试用例,\n        ", "attachments": [{"name": "log", "source": "06ce5bc8-1109-4bc4-9727-dfa59e216123-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'username': '000000000@qq.com', 'password': 'w123456789', 'expected': '账号或密码错误', 'description': '账号错误'}"}], "start": 1757575924173, "stop": 1757575924173, "uuid": "051e4565-6d10-4ff8-b8da-90d0172f3b3c", "historyId": "9e5b6a4a847c60234bd093c2ff861a4d", "testCaseId": "9b772e3c4d74e39c94b5c8b74ce1a0be", "fullName": "cases.app_ui.android.test_login.TestLogin#test_login", "labels": [{"name": "feature", "value": "登录模块"}, {"name": "parentSuite", "value": "cases.app_ui.android"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "wk"}, {"name": "thread", "value": "27072-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.app_ui.android.test_login"}]}