{"uuid": "9346a6ac-631e-40d8-abd6-4bd1e51d1a51", "children": ["69af2baf-8ce8-4548-9133-d60bf126c71a"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "TypeError: AppOperator.__init__() missing 2 required positional arguments: 'driver' and 'appium_hub'\n", "trace": "  File \"C:\\Users\\w8345\\.conda\\envs\\pytestAutoApi\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\w8345\\.conda\\envs\\pytestAutoApi\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\w8345\\.conda\\envs\\pytestAutoApi\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\w8345\\.conda\\envs\\pytestAutoApi\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\w8345\\.conda\\envs\\pytestAutoApi\\Lib\\site-packages\\_pytest\\fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\PytestAutoApi\\cases\\app_ui\\android\\test_login.py\", line 19, in setup\n    self.lg = LoginPage()\n              ^^^^^^^^^^^\n"}, "start": 1757574827185, "stop": 1757574828486}], "start": 1757574827185, "stop": 1757574828492}